In [1]:
import pandas as pd

#그래프에 한글 표현하기
import  matplotlib.pyplot as plt
import  matplotlib.font_manager as fm
import  matplotlib.font_manager as fm
font_name = fm.FontProperties(fname = "C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family = font_name)



#마이너스 표시하기
import  matplotlib as mlp
mlp.rcParams["axes.unicode_minus"]  = False

import numpy as np
import pandas  as pd
import seaborn as sns
##회귀분석
import statsmodels.api as sm
# 정규화
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.feature_selection import  RFE
from lightgbm import LGBMClassifier,  LGBMRegressor
from lightgbm import plot_importance, plot_metric, plot_tree
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.svm import SVR, SVC
import multiprocessing 
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LinearRegression
from scipy import stats
#사용법이 파이선과 다른 기존xgb를  파이선에 맞게 만들어 놓은 것
from  xgboost import XGBClassifier, XGBRegressor
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import RobustScaler

#변수영향도 그래프, 트리그래프 더 쉽게 그리게 해줌
from xgboost import plot_importance, plot_tree

from sklearn.metrics import mean_absolute_error, mean_squared_error

import shap

In [2]:
df = pd.read_csv("../완성본_안전도_회귀분석/1_절도폭력안전도.csv")

In [3]:
#R에서 뽑은 변수들만 출력 :12개
#일반 lm에서 pvalue값 0.05인 변수를 추가했다. (crm_wthr_바람,crm_clue_피해자신고)
df = df[["crm_clue_고소","crm_wthr_바람","crm_clue_현행범","crm_clue_피해자신고","vic_sx_2","vic_age_60세초과","cctv_개수",
         "배치인원_수","비상벨_개수",
        "일인가구수","기초수급_19세이하","외국인수", "score_절폭"]]

In [4]:
df

,crm_clue_고소,crm_wthr_바람,crm_clue_현행범,crm_clue_피해자신고,vic_sx_2,vic_age_60세초과,cctv_개수,배치인원_수,비상벨_개수,일인가구수,기초수급_19세이하,외국인수,score_절폭
0,148.0,1.0,774.0,4224.0,1912.0,318.0,4719,395,5.0,52811.0,39101,15295,78.30
1,91.0,0.0,409.0,2729.0,1063.0,297.0,2919,258,1.0,28612.0,39101,24040,70.10
2,143.0,0.0,850.0,3048.0,1413.0,484.0,4447,333,8.0,41116.0,39101,18967,73.40
3,111.0,1.0,170.0,1431.0,658.0,243.0,1218,185,11.0,20165.0,54889,4184,73.15
4,73.0,0.0,72.0,1047.0,446.0,218.0,913,142,12.0,21519.0,54889,3268,77.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,94.0,0.0,277.0,914.0,487.0,239.0,1855,176,499.0,24317.0,31361,7111,75.80
119,163.0,0.0,585.0,2700.0,1402.0,555.0,4469,406,1778.0,52196.0,46485,9785,71.85
120,84.0,0.0,468.0,1377.0,683.0,271.0,1563,236,339.0,18597.0,6833,11496,77.40
121,63.0,1.0,333.0,841.0,449.0,238.0,784,213,42.0,41063.0,5756,10641,74.60
122,114.0,1.0,37.0,1153.0,542.0,149.0,2527,178,39.0,39078.0,16060,9814,80.05

## ElasticNet (alpha=1)

In [5]:
# train, test 분리
X_train, X_test, y_train, y_test  = train_test_split(df.iloc[:,:-1], df["score_절폭"],test_size = 0.3, random_state=0)

In [6]:
elastic = ElasticNet(alpha=1)
elastic.fit(X_train, y_train)
mean_absolute_error(elastic.predict(X_test), y_test)

1.5188465546452612

# 20년도 예측

In [7]:
df_test = pd.read_csv("../머신러닝_20년도예측데이터/1_절도폭력_20년도test.csv")
df_test.head()

,관할서,연도,crm_clue_고소,crm_wthr_바람,crm_clue_현행범,crm_clue_피해자신고,vic_sx_2,vic_age_60세초과,cctv_개수,배치인원_수,비상벨_개수,일인가구수,기초수급_19세이하,외국인수,score_절폭
0,경기수원남부경찰서,2020,186.0,0.0,605.0,3923.0,1745.0,330.0,4719,395,85.0,65729,48972,9305,77.45
1,경기수원서부경찰서,2020,76.0,0.0,340.0,2565.0,1101.0,354.0,2919,258,66.0,32186,48972,14449,73.15
2,경기수원중부경찰서,2020,126.0,0.0,494.0,2633.0,1347.0,493.0,4447,333,52.0,45899,48972,11715,78.10
3,경남마산동부경찰서,2020,85.0,0.0,163.0,1325.0,595.0,281.0,1218,185,11.0,21943,80959,2099,75.55
4,경남마산중부경찰서,2020,65.0,0.0,51.0,876.0,383.0,231.0,913,142,14.0,22631,80959,1867,80.30

In [8]:
# 결과값
elastic.predict(df_test.iloc[:,2:-1])

array([77.83570672, 74.98686407, 75.71636452, 75.0178744 , 74.76404181,
       77.52163121, 75.62000127, 74.67301303, 77.23539086, 83.81211653,
       77.391982  , 74.52006994, 76.56406526, 73.60562905, 79.15667345,
       77.13101566, 76.61992851, 78.87058439, 79.18019402, 76.54016062,
       78.84167296, 76.65567205, 79.93934597, 81.22442305, 76.71493285,
       78.61829862, 81.94217739, 78.33432549, 79.57654375, 78.32133899,
       83.73126007, 79.27413031, 75.97896183, 79.59932266, 75.28727238,
       80.06982696, 76.22982582, 73.6616904 , 77.81680521, 77.95754653,
       79.79036154])

In [9]:
elastic.predict(df_test.iloc[:,2:-1])

array([77.83570672, 74.98686407, 75.71636452, 75.0178744 , 74.76404181,
       77.52163121, 75.62000127, 74.67301303, 77.23539086, 83.81211653,
       77.391982  , 74.52006994, 76.56406526, 73.60562905, 79.15667345,
       77.13101566, 76.61992851, 78.87058439, 79.18019402, 76.54016062,
       78.84167296, 76.65567205, 79.93934597, 81.22442305, 76.71493285,
       78.61829862, 81.94217739, 78.33432549, 79.57654375, 78.32133899,
       83.73126007, 79.27413031, 75.97896183, 79.59932266, 75.28727238,
       80.06982696, 76.22982582, 73.6616904 , 77.81680521, 77.95754653,
       79.79036154])