In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("6.범죄발생원표.csv")
df.head()

/opt/app-root/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (4,8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,jur_stn,crm,crm_wthr,crm_clue,vic_sx,vic_age,crm_loc,crm_tm,crm_date,5m_crm_yn
0,서울수서경찰서,위조외국통화행사,미상,진정,불상,,은행,09:00-11:59,20170101,
1,서울영등포경찰서,도로교통법위반,맑음,타인신고,불상,,노상,21:00-23:59,20170101,
2,서울양천경찰서,209015100,미상,피해자신고,남자,60세초과,노상,미상,20170101,
3,서울서초경찰서,폭행,미상,피해자신고,여자,40세이하,기타,21:00-23:59,20170101,폭력
4,서울동대문경찰서,사기,미상,진정,여자,30세이하,기타,미상,20170101,

In [6]:
df = df[df["crm_date"].astype(str).str.contains("2017|2018|2019")]
df.head()

,jur_stn,crm,crm_wthr,crm_clue,vic_sx,vic_age,crm_loc,crm_tm,crm_date,5m_crm_yn
0,서울수서경찰서,위조외국통화행사,미상,진정,불상,,은행,09:00-11:59,20170101,
1,서울영등포경찰서,도로교통법위반,맑음,타인신고,불상,,노상,21:00-23:59,20170101,
2,서울양천경찰서,209015100,미상,피해자신고,남자,60세초과,노상,미상,20170101,
3,서울서초경찰서,폭행,미상,피해자신고,여자,40세이하,기타,21:00-23:59,20170101,폭력
4,서울동대문경찰서,사기,미상,진정,여자,30세이하,기타,미상,20170101,

In [7]:
date = df["crm_date"].astype(str)
date

0           20170101
1           20170101
2           20170101
3           20170101
4           20170101
             ...
1073217    9/27/2019
1073218    10/4/2019
1073219    9/17/2019
1073220    9/14/2019
1073221    5/16/2019
Name: crm_date, Length: 1068240, dtype: object

In [8]:
# 날짜 정리

z = []
for i in date[-date.str.contains("/")]:
    b = list(i)
    b.insert(4,"/")
    b.insert(7,"/")
    a = "".join(b)
    z.append(a)
    
date[-date.str.contains("/")] = z

In [9]:
date = date[date.str.contains("/")]
date

0          2017/01/01
1          2017/01/01
2          2017/01/01
3          2017/01/01
4          2017/01/01
              ...
1073217     9/27/2019
1073218     10/4/2019
1073219     9/17/2019
1073220     9/14/2019
1073221     5/16/2019
Name: crm_date, Length: 1068240, dtype: object

In [10]:
df["crm_date"] = pd.to_datetime(date)
df.reset_index(drop=True, inplace = True)
df.tail()

,jur_stn,crm,crm_wthr,crm_clue,vic_sx,vic_age,crm_loc,crm_tm,crm_date,5m_crm_yn
1068235,경남진해경찰서,사기,미상,고소,2,60세이하,기타,미상,2019-09-27,
1068236,경남진해경찰서,폭행,맑음,피해자신고,3,,차안,00:00∼02:59,2019-10-04,폭력
1068237,경남마산동부경찰서,재물손괴,미상,피해자신고,2,60세이하,주택,12:00∼14:59,2019-09-17,폭력
1068238,경남마산중부경찰서,사기,미상,진정,1,50세이하,기타,12:00∼14:59,2019-09-14,
1068239,경남마산동부경찰서,강제추행,미상,고소,1,30세이하,기타,21:00∼23:59,2019-05-16,강간 및 강제추행

In [11]:
date = len(df)
a = []

for i in range(date):
    f = df["crm_date"][i].strftime("%Y%m%d")
    a.append(f)

In [12]:
df["crm_date"] = a
df.head()

,jur_stn,crm,crm_wthr,crm_clue,vic_sx,vic_age,crm_loc,crm_tm,crm_date,5m_crm_yn
0,서울수서경찰서,위조외국통화행사,미상,진정,불상,,은행,09:00-11:59,20170101,
1,서울영등포경찰서,도로교통법위반,맑음,타인신고,불상,,노상,21:00-23:59,20170101,
2,서울양천경찰서,209015100,미상,피해자신고,남자,60세초과,노상,미상,20170101,
3,서울서초경찰서,폭행,미상,피해자신고,여자,40세이하,기타,21:00-23:59,20170101,폭력
4,서울동대문경찰서,사기,미상,진정,여자,30세이하,기타,미상,20170101,

In [13]:
df.to_csv("6_범죄발생원표_날짜전처리_완성본")

In [14]:
df["crm_date"] = df["crm_date"].astype(str)
df_2017=df[df["crm_date"].str.contains("2017")].iloc[:,0:]
df_2018=df[df["crm_date"].str.contains("2018")].iloc[:,0:]
df_2019=df[df["crm_date"].str.contains("2019")].iloc[:,0:]

df_2017.head()

,jur_stn,crm,crm_wthr,crm_clue,vic_sx,vic_age,crm_loc,crm_tm,crm_date,5m_crm_yn
0,서울수서경찰서,위조외국통화행사,미상,진정,불상,,은행,09:00-11:59,20170101,
1,서울영등포경찰서,도로교통법위반,맑음,타인신고,불상,,노상,21:00-23:59,20170101,
2,서울양천경찰서,209015100,미상,피해자신고,남자,60세초과,노상,미상,20170101,
3,서울서초경찰서,폭행,미상,피해자신고,여자,40세이하,기타,21:00-23:59,20170101,폭력
4,서울동대문경찰서,사기,미상,진정,여자,30세이하,기타,미상,20170101,

In [15]:
df_2017["jur_stn"] = df_2017["jur_stn"].str.strip()
df_2018["jur_stn"] = df_2018["jur_stn"].str.strip()
df_2019["jur_stn"] = df_2019["jur_stn"].str.strip()

In [16]:
gr_2017_절폭 = df_2017[df_2017["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2018_절폭 = df_2018[df_2018["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2019_절폭 = df_2019[df_2019["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]

In [17]:
df_절폭 = pd.DataFrame({"관할서":gr_2017_절폭.index, "발생_17_절도폭력":gr_2017_절폭.values, "발생_18_절도폭력":gr_2018_절폭.values, 
              "발생_19_절도폭력":gr_2019_절폭.values})
df_절폭.head()

         관할서  발생_17_절도폭력  발생_18_절도폭력  발생_19_절도폭력
0  경기수원남부경찰서        5866        5670        5187
1  경기수원서부경찰서        3557        3498        3253
2  경기수원중부경찰서        4274        4298        3608
3  경남마산동부경찰서        1954        1950        1738
4  경남마산중부경찰서        1377        1391        1105

In [18]:
gr_2017_절폭 = df_2017[df_2017["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2018_절폭 = df_2018[df_2018["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2019_절폭 = df_2019[df_2019["5m_crm_yn"].isin(["절도","폭력"])].groupby("jur_stn",sort = True).count()["crm"]

In [19]:
df_절폭 = pd.DataFrame({"관할서":gr_2017_절폭.index, "발생_17_절도폭력":gr_2017_절폭.values, "발생_18_절도폭력":gr_2018_절폭.values, 
              "발생_19_절도폭력":gr_2019_절폭.values})
df_절폭.head()

         관할서  발생_17_절도폭력  발생_18_절도폭력  발생_19_절도폭력
0  경기수원남부경찰서        5866        5670        5187
1  경기수원서부경찰서        3557        3498        3253
2  경기수원중부경찰서        4274        4298        3608
3  경남마산동부경찰서        1954        1950        1738
4  경남마산중부경찰서        1377        1391        1105

In [20]:
gr_2017_강살 = df_2017[df_2017["5m_crm_yn"].isin(["강도","살인"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2018_강살 = df_2018[df_2018["5m_crm_yn"].isin(["강도","살인"])].groupby("jur_stn",sort = True).count()["crm"]
gr_2019_강살 = df_2019[df_2019["5m_crm_yn"].isin(["강도","살인"])].groupby("jur_stn",sort = True).count()["crm"]

In [21]:
df_강살 = pd.DataFrame({"관할서":gr_2017_강살.index, "발생_17_강도살인":gr_2017_강살.values, "발생_18_강도살인":gr_2018_강살.values, 
              "발생_19_강도살인":gr_2019_강살.values})
df_강살.head()

         관할서  발생_17_강도살인  발생_18_강도살인  발생_19_강도살인
0  경기수원남부경찰서          13          13          17
1  경기수원서부경찰서          10           9           8
2  경기수원중부경찰서          12          11           7
3  경남마산동부경찰서           7           3           7
4  경남마산중부경찰서           9          18           7

In [22]:
gr_2017_교통 = df_2017[df_2017["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]
gr_2018_교통 = df_2018[df_2018["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]
gr_2019_교통 = df_2019[df_2019["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]

In [23]:
df_교통 = pd.DataFrame({"관할서":gr_2017_교통.index, "발생_17_교통사고":gr_2017_교통.values, "발생_18_교통사고":gr_2018_교통.values, 
              "발생_19_교통사고":gr_2019_교통.values})
df_교통.head()

         관할서  발생_17_교통사고  발생_18_교통사고  발생_19_교통사고
0  경기수원남부경찰서        5507        5038        4224
1  경기수원서부경찰서        1991        2041        1942
2  경기수원중부경찰서        2999        3460        2745
3  경남마산동부경찰서        1192        1023        1026
4  경남마산중부경찰서        1238        1130        1015

In [28]:
gr_2017_질서 = df_2017[df_2017["5m_crm_yn"]==' ']
gr_2017_질서 = gr_2017_질서[-df_2017_질서["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]

In [29]:
gr_2018_질서 = df_2018[df_2018["5m_crm_yn"]==' ']
gr_2018_질서 = gr_2018_질서[-df_2018_질서["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]

gr_2019_질서 = df_2019[df_2019["5m_crm_yn"]==' ']
gr_2019_질서 = gr_2019_질서[-df_2019_질서["crm"].str.contains("교통|도로|사고|도주차량")].groupby("jur_stn",sort = True).count()["crm"]

In [31]:
df_질서 = pd.DataFrame({"관할서":gr_2017_질서.index, "발생_17_기초질서":gr_2017_질서.values, "발생_18_기초질서":gr_2018_질서.values, 
              "발생_19_기초질서":gr_2019_질서.values})

In [32]:
gr_2017_all = df_2017.groupby("jur_stn", sort = True).count()["crm"]
gr_2018_all = df_2018.groupby("jur_stn", sort = True).count()["crm"]
gr_2019_all = df_2019.groupby("jur_stn", sort = True).count()["crm"]

In [33]:
df_all = pd.DataFrame({"관할서":gr_2017_all.index, "발생_17_전반":gr_2017_all.values, "발생_18_전반":gr_2018_all.values, 
              "발생_19_전반":gr_2019_all.values})
df_all.head()

         관할서  발생_17_전반  발생_18_전반  발생_19_전반
0  경기수원남부경찰서     19756     17846     16148
1  경기수원서부경찰서     11254      9799      8727
2  경기수원중부경찰서     14233     12978     10411
3  경남마산동부경찰서      5914      5212      4495
4  경남마산중부경찰서      4718      4223      3219

In [34]:
df_범죄발생원표 = pd.concat([df_절폭, df_강살.iloc[:,1:] , df_교통.iloc[:,1:], df_질서.iloc[:,1:] , df_all.iloc[:,1:]], axis = 1)
df_범죄발생원표.head()

,관할서,발생_17_절도폭력,발생_18_절도폭력,발생_19_절도폭력,발생_17_강도살인,발생_18_강도살인,발생_19_강도살인,발생_17_교통사고,발생_18_교통사고,발생_19_교통사고,발생_17_기초질서,발생_18_기초질서,발생_19_기초질서,발생_17_전반,발생_18_전반,발생_19_전반
0,경기수원남부경찰서,5866,5670,5187,13,13,17,5507,5038,4224,8098,6840,6488,19756,17846,16148
1,경기수원서부경찰서,3557,3498,3253,10,9,8,1991,2041,1942,5524,4109,3420,11254,9799,8727
2,경기수원중부경찰서,4274,4298,3608,12,11,7,2999,3460,2745,6774,5081,3935,14233,12978,10411
3,경남마산동부경찰서,1954,1950,1738,7,3,7,1192,1023,1026,2697,2168,1650,5914,5212,4495
4,경남마산중부경찰서,1377,1391,1105,9,18,7,1238,1130,1015,2048,1635,1054,4718,4223,3219

In [35]:
df_범죄발생원표.to_csv("6_범죄발생원표_전처리완성본")

In [36]:
df = pd.read_csv("6_범죄발생원표_전처리완성본")

In [41]:
df.set_index("관할서", inplace=True)
df.head()

KeyError: "None of ['관할서'] are in the columns"