In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
df_one = pd.read_csv('16.5개시도_인구데이터(외국인).csv')

In [3]:
df_one.head()

,sido,sgg,foreigner_all(2017),foreigner_M(2017),foreigner_F(2017),foreigner_all(2018),foreigner_M(2018),foreigner_F(2018),foreigner_all(2019),foreigner_M(2019),foreigner_F(2019)
0,서울특별시,종로구,10979,4913,6066,12056,5536,6520,13159,5818,7341
1,서울특별시,중구,10265,4804,5461,11988,5735,6253,12559,6025,6534
2,서울특별시,용산구,16005,8712,7293,19126,10879,8247,20503,11621,8882
3,서울특별시,성동구,10436,5042,5394,11307,5403,5904,11774,5610,6164
4,서울특별시,광진구,18399,8323,10076,19729,9032,10697,20925,9474,11451

In [4]:

df_one.drop(['sido'], axis = 1, inplace=True)
df_one.groupby('sgg').mean()

,foreigner_all(2017),foreigner_M(2017),foreigner_F(2017),foreigner_all(2018),foreigner_M(2018),foreigner_F(2018),foreigner_all(2019),foreigner_M(2019),foreigner_F(2019)
sgg,,,,,,,,,
강남구,7655,3706,3949,8814,4623,4191,9725,5354,4371
강동구,5887,2791,3096,6384,3034,3350,6669,3198,3471
강북구,4443,1719,2724,4947,1971,2976,5346,2088,3258
강서구,8682,4114,4568,9179,4347,4832,9043,4156,4887
관악구,24475,11466,13009,25418,11872,13546,25352,11877,13475
광진구,18399,8323,10076,19729,9032,10697,20925,9474,11451
구로구,41907,22656,19251,45686,25064,20622,46036,25097,20939
금천구,25443,13673,11770,27524,14990,12534,27554,14956,12598
노원구,4731,2092,2639,5828,2613,3215,6279,2878,3401
도봉구,2629,1059,1570,2951,1199,1752,3320,1380,1940
동대문구,17942,7483,10459,19848,8324,11524,21049,8852,12197
동작구,16009,7454,8555,17321,8117,9204,17972,8292,9680
마포구,11960,5015,6945,12776,5375,7401,14307,6079,8228
서대문구,13152,4812,8340,14366,5230,9136,16319,6031,10288
서초구,6538,3168,3370,7143,3604,3539,7935,4273,3662
성동구,10436,5042,5394,11307,5403,5904,11774,5610,6164
성북구,13191,5694,7497,14523,6173,8350,15552,6621,8931
세종시,5290,3130,2160,6486,3887,2599,7829,4860,2969
송파구,9418,4476,4942,10123,4937,5186,10917,5425,5492
수원시 권선구,12741,6569,6172,14701,7546,7155,15339,7914,7425
수원시 영통구,8508,4648,3860,9182,4989,4193,9983,5268,4715
수원시 장안구,8435,4467,3968,9822,5240,4582,10413,5475,4938
수원시 팔달구,18908,10124,8784,19984,10870,9114,20451,11174,9277
양천구,5468,2468,3000,5681,2594,3087,6221,2867,3354
영등포구,46708,24709,21999,49151,26406,22745,48180,25835,22345
용산구,16005,8712,7293,19126,10879,8247,20503,11621,8882
은평구,5592,2425,3167,5970,2634,3336,6390,2793,3597
종로구,10979,4913,6066,12056,5536,6520,13159,5818,7341
중구,10265,4804,5461,11988,5735,6253,12559,6025,6534
중랑구,6013,2475,3538,6586,2728,3858,7091,2962,4129
진주시,5638,3464,2174,6492,4036,2456,7152,4284,2868
창원시 마산합포구,2583,1565,1018,2873,1726,1147,3145,1882,1263
창원시 마산회원구,2770,1635,1135,2770,1614,1156,2871,1611,1260
창원시 성산구,4937,3608,1329,5101,3642,1459,5191,3635,1556
창원시 의창구,4834,3010,1824,5074,3030,2044,5100,2991,2109
창원시 진해구,4344,2855,1489,4651,2951,1700,4917,3149,1768

In [9]:
df_one.columns=["구","2017_외국인_계","2017_외국인_남","2017_외국인_여","2018_외국인_계","2018_외국인_남","2018_외국인_여","2019_외국인_계","2019_외국인_남","2019_외국인_여"]

In [11]:
df_one.groupby('구').mean()

,2017_외국인_계,2017_외국인_남,2017_외국인_여,2018_외국인_계,2018_외국인_남,2018_외국인_여,2019_외국인_계,2019_외국인_남,2019_외국인_여
구,,,,,,,,,
강남구,7655,3706,3949,8814,4623,4191,9725,5354,4371
강동구,5887,2791,3096,6384,3034,3350,6669,3198,3471
강북구,4443,1719,2724,4947,1971,2976,5346,2088,3258
강서구,8682,4114,4568,9179,4347,4832,9043,4156,4887
관악구,24475,11466,13009,25418,11872,13546,25352,11877,13475
광진구,18399,8323,10076,19729,9032,10697,20925,9474,11451
구로구,41907,22656,19251,45686,25064,20622,46036,25097,20939
금천구,25443,13673,11770,27524,14990,12534,27554,14956,12598
노원구,4731,2092,2639,5828,2613,3215,6279,2878,3401
도봉구,2629,1059,1570,2951,1199,1752,3320,1380,1940
동대문구,17942,7483,10459,19848,8324,11524,21049,8852,12197
동작구,16009,7454,8555,17321,8117,9204,17972,8292,9680
마포구,11960,5015,6945,12776,5375,7401,14307,6079,8228
서대문구,13152,4812,8340,14366,5230,9136,16319,6031,10288
서초구,6538,3168,3370,7143,3604,3539,7935,4273,3662
성동구,10436,5042,5394,11307,5403,5904,11774,5610,6164
성북구,13191,5694,7497,14523,6173,8350,15552,6621,8931
세종시,5290,3130,2160,6486,3887,2599,7829,4860,2969
송파구,9418,4476,4942,10123,4937,5186,10917,5425,5492
수원시 권선구,12741,6569,6172,14701,7546,7155,15339,7914,7425
수원시 영통구,8508,4648,3860,9182,4989,4193,9983,5268,4715
수원시 장안구,8435,4467,3968,9822,5240,4582,10413,5475,4938
수원시 팔달구,18908,10124,8784,19984,10870,9114,20451,11174,9277
양천구,5468,2468,3000,5681,2594,3087,6221,2867,3354
영등포구,46708,24709,21999,49151,26406,22745,48180,25835,22345
용산구,16005,8712,7293,19126,10879,8247,20503,11621,8882
은평구,5592,2425,3167,5970,2634,3336,6390,2793,3597
종로구,10979,4913,6066,12056,5536,6520,13159,5818,7341
중구,10265,4804,5461,11988,5735,6253,12559,6025,6534
중랑구,6013,2475,3538,6586,2728,3858,7091,2962,4129
진주시,5638,3464,2174,6492,4036,2456,7152,4284,2868
창원시 마산합포구,2583,1565,1018,2873,1726,1147,3145,1882,1263
창원시 마산회원구,2770,1635,1135,2770,1614,1156,2871,1611,1260
창원시 성산구,4937,3608,1329,5101,3642,1459,5191,3635,1556
창원시 의창구,4834,3010,1824,5074,3030,2044,5100,2991,2109
창원시 진해구,4344,2855,1489,4651,2951,1700,4917,3149,1768

In [12]:
df_one.set_index("구")

,2017_외국인_계,2017_외국인_남,2017_외국인_여,2018_외국인_계,2018_외국인_남,2018_외국인_여,2019_외국인_계,2019_외국인_남,2019_외국인_여
구,,,,,,,,,
종로구,10979,4913,6066,12056,5536,6520,13159,5818,7341
중구,10265,4804,5461,11988,5735,6253,12559,6025,6534
용산구,16005,8712,7293,19126,10879,8247,20503,11621,8882
성동구,10436,5042,5394,11307,5403,5904,11774,5610,6164
광진구,18399,8323,10076,19729,9032,10697,20925,9474,11451
동대문구,17942,7483,10459,19848,8324,11524,21049,8852,12197
중랑구,6013,2475,3538,6586,2728,3858,7091,2962,4129
성북구,13191,5694,7497,14523,6173,8350,15552,6621,8931
강북구,4443,1719,2724,4947,1971,2976,5346,2088,3258
도봉구,2629,1059,1570,2951,1199,1752,3320,1380,1940
노원구,4731,2092,2639,5828,2613,3215,6279,2878,3401
은평구,5592,2425,3167,5970,2634,3336,6390,2793,3597
서대문구,13152,4812,8340,14366,5230,9136,16319,6031,10288
마포구,11960,5015,6945,12776,5375,7401,14307,6079,8228
양천구,5468,2468,3000,5681,2594,3087,6221,2867,3354
강서구,8682,4114,4568,9179,4347,4832,9043,4156,4887
구로구,41907,22656,19251,45686,25064,20622,46036,25097,20939
금천구,25443,13673,11770,27524,14990,12534,27554,14956,12598
영등포구,46708,24709,21999,49151,26406,22745,48180,25835,22345
동작구,16009,7454,8555,17321,8117,9204,17972,8292,9680
관악구,24475,11466,13009,25418,11872,13546,25352,11877,13475
서초구,6538,3168,3370,7143,3604,3539,7935,4273,3662
강남구,7655,3706,3949,8814,4623,4191,9725,5354,4371
송파구,9418,4476,4942,10123,4937,5186,10917,5425,5492
강동구,5887,2791,3096,6384,3034,3350,6669,3198,3471
세종시,5290,3130,2160,6486,3887,2599,7829,4860,2969
수원시 장안구,8435,4467,3968,9822,5240,4582,10413,5475,4938
수원시 권선구,12741,6569,6172,14701,7546,7155,15339,7914,7425
수원시 팔달구,18908,10124,8784,19984,10870,9114,20451,11174,9277
수원시 영통구,8508,4648,3860,9182,4989,4193,9983,5268,4715
진주시,5638,3464,2174,6492,4036,2456,7152,4284,2868
창원시 의창구,4834,3010,1824,5074,3030,2044,5100,2991,2109
창원시 성산구,4937,3608,1329,5101,3642,1459,5191,3635,1556
창원시 마산합포구,2583,1565,1018,2873,1726,1147,3145,1882,1263
창원시 마산회원구,2770,1635,1135,2770,1614,1156,2871,1611,1260
창원시 진해구,4344,2855,1489,4651,2951,1700,4917,3149,1768

In [13]:
np.random.seed(0)
df1 = pd.DataFrame(np.round(np.random.randn(36, 9), 3),
                   columns=[["2017", "2017","2017","2018","2018","2018","2019","2019","2019"],
                            ["2017_외국인_계","2017_외국인_남","2017_외국인_여","2018_외국인_계","2018_외국인_남","2018_외국인_여","2019_외국인_계","2019_외국인_남","2019_외국인_여"]])
df1  ##### 구가 사라짐 ㅠㅠㅠ

         2017                             2018                        \
   2017_외국인_계 2017_외국인_남 2017_외국인_여 2018_외국인_계 2018_외국인_남 2018_외국인_여
0       1.764      0.400      0.979      2.241      1.868     -0.977
1       0.411      0.144      1.454      0.761      0.122      0.444
2       0.313     -0.854     -2.553      0.654      0.864     -0.742
3      -0.187      1.533      1.469      0.155      0.378     -0.888
4       1.230      1.202     -0.387     -0.302     -1.049     -1.420
5      -0.438     -1.253      0.777     -1.614     -0.213     -0.895
6      -0.028      0.428      0.067      0.302     -0.634     -0.363
7      -1.726      0.177     -0.402     -1.630      0.463     -0.907
8       1.139     -1.235      0.402     -0.685     -0.871     -0.579
9       0.901      0.466     -1.536      1.488      1.896      1.179
10     -0.403      1.222      0.208      0.977      0.356      0.707
11      0.402      1.883     -1.348     -1.270      0.969     -1.173
12      1.923      1.481      1.868      0.906     -0.861      1.910
13     -0.155      0.614      0.922      0.376     -1.099      0.298
14     -0.435      1.849      0.672      0.407     -0.770      0.539
15      0.676      0.577     -0.208      0.396     -1.093     -1.491
16      2.383      0.944     -0.913      1.117     -1.316     -0.462
17     -0.826     -0.098     -0.663      1.127     -1.080     -1.147
18      0.949      0.088     -1.225      0.844     -1.000     -1.545
19      0.319      0.857     -0.651     -1.034      0.682     -0.803
20     -0.354     -1.375     -0.644     -2.223      0.625     -1.602
21      1.543     -1.293      0.267     -0.039     -1.168      0.523
22      2.163      1.337     -0.369     -0.239      1.100      0.655
23     -0.738      0.280     -0.098      0.910      0.317      0.786
24     -0.017      0.379      2.259     -0.042     -0.956     -0.346
25      0.063      0.157      0.232     -0.597     -0.238     -1.424
26     -1.156      0.781      1.494     -2.070      0.426      0.677
27     -0.298     -0.309     -1.676      1.152      1.080     -0.813
28      0.142     -0.319      0.692      0.695     -0.726     -1.383
29     -0.507     -0.596     -0.053     -1.936      0.189      0.524
30      0.399     -2.773      1.956      0.390     -0.652     -0.391
31      2.064     -0.111      1.020     -0.692      1.536      0.286
32      0.690      1.302     -0.628     -0.481      2.304     -1.060
33      0.583     -0.399      0.370     -1.307      1.658     -0.118
34     -1.334     -1.347      0.694     -0.160     -0.134      1.078
35      0.094     -0.042     -0.287     -0.062     -0.107     -0.720

         2019
   2019_외국인_계 2019_외국인_남 2019_외국인_여
0       0.950     -0.151     -0.103
1       0.334      1.494     -0.205
2       2.270     -1.454      0.046
3      -1.981     -0.348      0.156
4      -1.706      1.951     -0.510
5       0.387     -0.511     -1.181
6      -0.672     -0.360     -0.813
7       0.052      0.729      0.129
8      -0.312      0.056     -1.165
9      -0.180     -1.071      1.054
10      0.011      1.786      0.127
11      1.944     -0.414     -0.747
12     -0.268      0.802      0.947
13      1.326     -0.695     -0.150
14     -0.674      0.032     -0.636
15      0.439      0.167      0.635
16     -0.068      1.713     -0.745
17     -0.438     -0.498      1.930
18      1.188      0.317      0.921
19     -0.690     -0.456      0.017
20     -1.104      0.052     -0.740
21     -0.172      0.772      0.824
22      0.640     -1.617     -0.024
23     -0.466     -0.944     -0.410
24     -0.464      0.481     -1.541
25     -0.493     -0.543      0.416
26     -0.637     -0.397     -0.133
27     -1.466      0.521     -0.576
28     -1.583      0.610     -1.189
29      0.088     -0.311      0.097
30      0.494     -0.116     -2.031
31      0.609     -1.045      1.211
32     -0.136      1.137      0.098
33     -0.680      0.666     -0.461
34     -1.127     -0.731     -0.385
35     -0.813      0.275     -0.891